- hosts: all
  gather_facts: false
  tasks:
    - name: stat module help to find the file info
      stat:
        path: /var/run
      register: your_variable

    # for your reference, check the outputs of these
    - debug: var=your_variable.stat

    - shell: echo "{{your_variable.stat}}" > /tmp/by_ansible

---

- name: help me fix it playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: alternative way to gather facts about remote host
      setup: filter='ansible_dist*' 
      register: facts

    - debug: var=facts.ansible_facts.ansible_distribution
    - shell: echo "{{facts.ansible_facts.ansible_distribution}}" > /tmp/output.txt

---

- name: print_dns server
  hosts: all
  tasks:
    - shell: "echo {{ hostvars['node01.host'].dns_server }} >> /tmp/variable.txt"